In [52]:
import pandas as pd
import numpy as np
from pandas import Series, DataFrame

print(pd.__version__)

3.0.5

In [106]:
df = pd.read_csv(r"./data/salary.csv")

# df.describe()

# df.info()

# df.head()

# df.tail()

# df.count()
df["City"].value_counts()

City
Chennai       4
Bangalore     1
Coimbatore    1
Name: count, dtype: int64

In [ ]:
df.columns[0:3]
df[df.columns[0:3]]

In [ ]:
df.loc[0:5, "Name":"City"]
df.iloc[0:5, 0:3]

In [ ]:
df["Salary"]
df.Salary.sum()
df.Salary.mean()
df.Salary.median()

In [ ]:
df.isnull()
df.isna()
df.notnull()

In [ ]:
# df["Age"].fillna(0)

# df["Age"].mean()
# df["Age"].fillna(df["Age"].mean())

df.fillna({ "Age": 0, "City": "" })

# df.fillna({ "Age": 0, "City": "" }, inplace=True)
df

In [70]:
df.duplicated()
# df.drop_duplicates("Name", inplace=True)
# df.drop_duplicates(keep=False)
# df.drop_duplicates(keep="first")
df.drop_duplicates(keep="last")

      Name   Age        City Department   Salary  Experience
0     Arun  21.0     Chennai         IT  35000.0         1.0
1    Priya  24.0   Bangalore         HR  42000.0         3.0
3    Sneha  23.0  Coimbatore         IT      NaN         4.0
4  Karthik  25.0         NaN  Marketing  50000.0         5.0
5    Divya  21.0     Chennai    Finance  36000.0         NaN

In [79]:
# df.dropna(how="all")
df.dropna()

      Name   Age        City Department   Salary  Experience
0     Arun  21.0     Chennai         IT  35000.0         1.0
1    Priya  24.0   Bangalore         HR  42000.0         3.0
2    Rahul   NaN     Chennai    Finance  38000.0         2.0
3    Sneha  23.0  Coimbatore         IT      NaN         4.0
4  Karthik  25.0         NaN  Marketing  50000.0         5.0
5    Divya  21.0     Chennai    Finance  36000.0         NaN
6    Rahul   NaN     Chennai    Finance  38000.0         2.0

In [80]:
df["City"].replace("Bangalore", "Bengaluru")

0       Chennai
1     Bengaluru
2       Chennai
3    Coimbatore
4           NaN
5       Chennai
6       Chennai
Name: City, dtype: str

In [83]:
# df.sort_values(["Age", "City"])
df.sort_index()
df.sort_values("Age")

      Name   Age        City Department   Salary  Experience
0     Arun  21.0     Chennai         IT  35000.0         1.0
5    Divya  21.0     Chennai    Finance  36000.0         NaN
3    Sneha  23.0  Coimbatore         IT      NaN         4.0
1    Priya  24.0   Bangalore         HR  42000.0         3.0
4  Karthik  25.0         NaN  Marketing  50000.0         5.0
2    Rahul   NaN     Chennai    Finance  38000.0         2.0
6    Rahul   NaN     Chennai    Finance  38000.0         2.0

In [96]:
orders = pd.read_csv(r"./data/orders.csv")
customers = pd.read_csv(r"./data/customers.csv")

# orders.merge(customers)

pd.merge(orders, customers, left_on="customer_id", right_on="customer_id", how="right")

,order_id,customer_id,product_id,quantity,order_date,name,city,segment
0,O001,C001,P001,1,05-01-2026,Arun,Chennai,Consumer
1,O002,C002,P002,2,06-01-2026,Priya,Bangalore,Corporate
2,O003,C003,P005,1,07-01-2026,Ravi,Chennai,Consumer
3,O004,C001,P003,2,10-01-2026,Arun,Chennai,Consumer
4,O005,C004,P006,1,12-01-2026,Meena,Hyderabad,Corporate
5,O006,C005,P004,2,15-01-2026,Karthik,Bangalore,Consumer
6,O007,C006,P007,10,18-01-2026,Divya,Coimbatore,Consumer
7,O008,C007,P001,2,20-01-2026,Suresh,Chennai,Corporate
8,O009,C002,P008,20,22-01-2026,Priya,Bangalore,Corporate
9,O010,C008,P005,2,25-01-2026,Anitha,Madurai,Consumer
10,O011,C003,P002,3,01-02-2026,Ravi,Chennai,Consumer
11,O012,C005,P006,1,03-02-2026,Karthik,Bangalore,Consumer
12,O013,C001,P007,15,05-02-2026,Arun,Chennai,Consumer
13,O014,C004,P004,3,08-02-2026,Meena,Hyderabad,Corporate
14,O015,C007,P003,5,10-02-2026,Suresh,Chennai,Corporate

In [101]:
df.groupby("City")["Salary"].mean()

City
Bangalore     42000.0
Chennai       36750.0
Coimbatore        NaN
Name: Salary, dtype: float64

In [104]:
df["City"].dropna().unique()

<StringArray>
['Chennai', 'Bangalore', 'Coimbatore']
Length: 3, dtype: str

Sorting
- By Index
- By Value

Math
- Min, Max
- Sum, Mean, Median
- Count

- Unique
- Value Counts

Missing Values
- isnull
- notnull
- dropna
- fillna

Duplicates
- drop duplicates
- duplicated

Replacing Values
- replace

Merge

Group
Agg