In [2]:
import pandas as pd
from pandas import Series, DataFrame

print(pd.__version__)

3.0.5

In [3]:
orders = pd.read_csv(r"./data/orders.csv")
orders

   order_id customer_id product_id  quantity  order_date
0      O001        C001       P001         1  05-01-2026
1      O002        C002       P002         2  06-01-2026
2      O003        C003       P005         1  07-01-2026
3      O004        C001       P003         2  10-01-2026
4      O005        C004       P006         1  12-01-2026
5      O006        C005       P004         2  15-01-2026
6      O007        C006       P007        10  18-01-2026
7      O008        C007       P001         2  20-01-2026
8      O009        C002       P008        20  22-01-2026
9      O010        C008       P005         2  25-01-2026
10     O011        C003       P002         3  01-02-2026
11     O012        C005       P006         1  03-02-2026
12     O013        C001       P007        15  05-02-2026
13     O014        C004       P004         3  08-02-2026
14     O015        C007       P003         5  10-02-2026

In [4]:
customers = pd.read_csv(r"./data/customers.csv")
customers

  customer_id     name        city    segment
0        C001     Arun     Chennai   Consumer
1        C002    Priya   Bangalore  Corporate
2        C003     Ravi     Chennai   Consumer
3        C004    Meena   Hyderabad  Corporate
4        C005  Karthik   Bangalore   Consumer
5        C006    Divya  Coimbatore   Consumer
6        C007   Suresh     Chennai  Corporate
7        C008   Anitha     Madurai   Consumer

In [7]:
products = pd.read_csv(r"./data/products.csv")
products

  product_id  product_name     category  price
0       P001        Laptop  Electronics  55000
1       P002         Mouse  Electronics    800
2       P003      Keyboard  Electronics   1500
3       P004       Monitor  Electronics  12000
4       P005  Office Chair    Furniture   8500
5       P006          Desk    Furniture  15000
6       P007      Notebook   Stationery    120
7       P008           Pen   Stationery     50

In [9]:
sales = orders.merge(customers, on="customer_id").merge(products, on="product_id")
sales

,order_id,customer_id,product_id,quantity,order_date,name,city,segment,product_name,category,price
0,O001,C001,P001,1,05-01-2026,Arun,Chennai,Consumer,Laptop,Electronics,55000
1,O002,C002,P002,2,06-01-2026,Priya,Bangalore,Corporate,Mouse,Electronics,800
2,O003,C003,P005,1,07-01-2026,Ravi,Chennai,Consumer,Office Chair,Furniture,8500
3,O004,C001,P003,2,10-01-2026,Arun,Chennai,Consumer,Keyboard,Electronics,1500
4,O005,C004,P006,1,12-01-2026,Meena,Hyderabad,Corporate,Desk,Furniture,15000
5,O006,C005,P004,2,15-01-2026,Karthik,Bangalore,Consumer,Monitor,Electronics,12000
6,O007,C006,P007,10,18-01-2026,Divya,Coimbatore,Consumer,Notebook,Stationery,120
7,O008,C007,P001,2,20-01-2026,Suresh,Chennai,Corporate,Laptop,Electronics,55000
8,O009,C002,P008,20,22-01-2026,Priya,Bangalore,Corporate,Pen,Stationery,50
9,O010,C008,P005,2,25-01-2026,Anitha,Madurai,Consumer,Office Chair,Furniture,8500
10,O011,C003,P002,3,01-02-2026,Ravi,Chennai,Consumer,Mouse,Electronics,800
11,O012,C005,P006,1,03-02-2026,Karthik,Bangalore,Consumer,Desk,Furniture,15000
12,O013,C001,P007,15,05-02-2026,Arun,Chennai,Consumer,Notebook,Stationery,120
13,O014,C004,P004,3,08-02-2026,Meena,Hyderabad,Corporate,Monitor,Electronics,12000
14,O015,C007,P003,5,10-02-2026,Suresh,Chennai,Corporate,Keyboard,Electronics,1500

In [12]:
sales["total"] = sales["quantity"] * sales["price"]
sales

,order_id,customer_id,product_id,quantity,order_date,name,city,segment,product_name,category,price,total
0,O001,C001,P001,1,05-01-2026,Arun,Chennai,Consumer,Laptop,Electronics,55000,55000
1,O002,C002,P002,2,06-01-2026,Priya,Bangalore,Corporate,Mouse,Electronics,800,1600
2,O003,C003,P005,1,07-01-2026,Ravi,Chennai,Consumer,Office Chair,Furniture,8500,8500
3,O004,C001,P003,2,10-01-2026,Arun,Chennai,Consumer,Keyboard,Electronics,1500,3000
4,O005,C004,P006,1,12-01-2026,Meena,Hyderabad,Corporate,Desk,Furniture,15000,15000
5,O006,C005,P004,2,15-01-2026,Karthik,Bangalore,Consumer,Monitor,Electronics,12000,24000
6,O007,C006,P007,10,18-01-2026,Divya,Coimbatore,Consumer,Notebook,Stationery,120,1200
7,O008,C007,P001,2,20-01-2026,Suresh,Chennai,Corporate,Laptop,Electronics,55000,110000
8,O009,C002,P008,20,22-01-2026,Priya,Bangalore,Corporate,Pen,Stationery,50,1000
9,O010,C008,P005,2,25-01-2026,Anitha,Madurai,Consumer,Office Chair,Furniture,8500,17000
10,O011,C003,P002,3,01-02-2026,Ravi,Chennai,Consumer,Mouse,Electronics,800,2400
11,O012,C005,P006,1,03-02-2026,Karthik,Bangalore,Consumer,Desk,Furniture,15000,15000
12,O013,C001,P007,15,05-02-2026,Arun,Chennai,Consumer,Notebook,Stationery,120,1800
13,O014,C004,P004,3,08-02-2026,Meena,Hyderabad,Corporate,Monitor,Electronics,12000,36000
14,O015,C007,P003,5,10-02-2026,Suresh,Chennai,Corporate,Keyboard,Electronics,1500,7500

In [21]:
sales["total"].agg(["sum", "min", "max", "mean"])

sum     299000.000000
min       1000.000000
max     110000.000000
mean     19933.333333
Name: total, dtype: float64

In [37]:
sales[["quantity","total", "category"]].groupby("category").agg(["sum", "min", "max"])

            quantity           total
                 sum min max     sum   min     max
category
Electronics       20   1   5  239500  1600  110000
Furniture          5   1   2   55500  8500   17000
Stationery        45  10  20    4000  1000    1800

In [41]:
sales.query('city == "Chennai"').describe()
df.groupby(["segment", "category"]).agg(
    total_sales=("sales", "sum"),
    total_orders=("order_id", "count")
)

        quantity         price          total
count   7.000000      7.000000       7.000000
mean    4.142857  17488.571429   26885.714286
std     4.980916  25776.130708   41254.512019
min     1.000000    120.000000    1800.000000
25%     1.500000   1150.000000    2700.000000
50%     2.000000   1500.000000    7500.000000
75%     4.000000  31750.000000   31750.000000
max    15.000000  55000.000000  110000.000000

In [44]:
sales.groupby(["segment", "category"]).agg(
    total_sales=("total", "sum"),
    total_orders=("order_id", "count")
)

                       total_sales  total_orders
segment   category
Consumer  Electronics        84400             4
          Furniture          40500             3
          Stationery          3000             2
Corporate Electronics       155100             4
          Furniture          15000             1
          Stationery          1000             1

In [58]:
sales.groupby(["customer_id", "name", "city"]).agg(total_sales = ("total", "sum")).sort_values("total_sales", ascending=False)

                                total_sales
customer_id name    city
C007        Suresh  Chennai          117500
C001        Arun    Chennai           59800
C004        Meena   Hyderabad         51000
C005        Karthik Bangalore         39000
C008        Anitha  Madurai           17000
C003        Ravi    Chennai           10900
C002        Priya   Bangalore          2600
C006        Divya   Coimbatore         1200